# -----------------------------------------
# docker-compose.yml
# -----------------------------------------
# Run these commands in the same directory:
# sudo dockerd               # Start Docker daemon (if not running)
# docker compose up --build  # Build and start all containers
# -----------------------------------------

# Use Docker Compose version 3.9 syntax (latest stable for most setups)
version: "3.9"

# Define all services (containers) that will run
services:

  # -----------------------------
  # Backend API Service
  # -----------------------------
  api:
    # Build the image using the local Dockerfile
    build:
      context: .             # Use current directory as build context
      dockerfile: Dockerfile # Specify which Dockerfile to use (optional if named "Dockerfile")

    # Name the container for easier reference
    container_name: project_api

    # Expose ports between host and container
    # Format: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "5000:5000"          # Maps local port 5000 → container port 5000

    # Load environment variables from external .env file
    env_file:
      - .env                 # Path to .env file containing key=value pairs

    # Ensure the API waits until the database container is ready
    depends_on:
      - db                   # db service must start before this one

    # Mount local folders into the container
    volumes:
      - ./app:/app           # Mount local "app" directory to /app inside container
      - ./logs:/app/logs     # Mount local "logs" directory for persistent logs

    # Automatically restart container if it stops unexpectedly
    restart: unles
